version: '2.1'
services:
  app:
    restart: always
    container_name: resuelve-fc
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    entrypoint: ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
  test:
    build: .
    volumes:
      - .:/app
    command: nosetests -v
    depends_on:
            - app

